services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./organizations.db:/app/organizations.db
    environment:
      - DATABASE_URL=sqlite:///organizations.db
    restart: unless-stopped 